name: Sync Kobo Data

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:     # Allow manual runs

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests pandas
      
    - name: Run Kobo Sync
      env:
        KOBO_API_TOKEN: ${{ secrets.KOBO_API_TOKEN }}
      run: |
        python sync_kobo.py
        echo "Current directory contents:"
        ls -la
        [ -f kobo_data.csv ] && echo "CSV exists!" || echo "CSV missing!"
        
    - name: Commit and Push Changes
      if: success()
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add kobo_data.csv
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update Kobo data"
          git push
        fi
