name: Sync Kobo Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual runs

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests pandas
      
    - name: Run Kobo Sync
      env:
        KOBO_API_TOKEN: ${{ secrets.KOBO_API_TOKEN }}  # Your token: [YOUR_ACTUAL_API_TOKEN]
      run: python sync_kobo.py
      
    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add kobo_data.csv
        git commit -m "Update Kobo data" || echo "No changes to commit"
        git push
