name: Sync Kobo Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Kobo Sync Script
        env:
          KOBO_API_TOKEN: ${{ edac13bbcd3ba6d893c5881597e740a338e2ca1a }}
        run: python sync_kobo.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kobo_data.csv
          git commit -m "Update Kobo data"
          git push
